documentation:
  - changed-files:
      - any-glob-to-any-file: ["**/*.md"]

github_actions:
  - changed-files:
      - any-glob-to-any-file: [".github/workflows/**", ".github/labeler.yml"]

tests:
  - changed-files:
      - any-glob-to-any-file: ["**/test/**"]

shell:
  - changed-files:
      - any-glob-to-any-file: ["**/*.sh", "tint"]

python:
  - changed-files:
      - any-glob-to-any-file: ["**/*.py"]
