documentation:
  - changed-files:
      - any-glob-to-any-file: ["**/*.md"]

github actions:
  - changed-files:
      - any-glob-to-any-file: [".github/workflows/**"]

tests:
  - changed-files:
      - any-glob-to-any-file: ["**/test/**"]

shell:
  - changed-files:
      - any-glob-to-any-file: ["**/*.sh"]

python:
  - changed-files:
      - any-glob-to-any-file: ["**/*.py"]
